apiVersion: 1

datasources:
  - name: Treadmill Data
    uid: treadmill
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /data/treadmill.db
    editable: false
